name: APT
channels:
  - defaults
  - pytorch
  - intel
  - anaconda
  - conda-forge
dependencies:
  - conda
  - python=3.7.7
  - conda-build
  - pyyaml
  - ipython
  - numpy=1.20
  - torchvision=0.7.0
  - pytorch=1.6.0
  - cudatoolkit=10.1
  - tensorflow==2.3.0
  - pip=22
  - mkl_fft
  - mkl_random
  - mkl-service
